name: Snyk
description: Runs vulnerability scans on dependencies and docker images
author: https://github.com/seek-oss
requirements:
  - docker
  - jq
configuration:
  properties:
    block:
      type: boolean
    language:
      type: string
    token:
      type: string
    path:
      type: string
    severity:
      type: string
    artifactoryUsername:
      type: string
    artifactoryPassword:
      type: string
    team:
      type: string