#!/usr/bin/env bash

echo 'Validating environment variables'

if [[ -n "$BUILDKITE_PLUGIN_SNYK_BLOCK" ]];
then
  echo "Block: $BUILDKITE_PLUGIN_SNYK_BLOCK"
  export BLOCK=$BUILDKITE_PLUGIN_SNYK_BLOCK
fi
  
if [[ -n "$BUILDKITE_PLUGIN_SNYK_LANGUAGE" ]]; 
then
  echo "Language: $BUILDKITE_PLUGIN_SNYK_LANGUAGE"
  export LANGUAGE=$BUILDKITE_PLUGIN_SNYK_LANGUAGE
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_ORG" ]]; 
then
  echo "Org: $BUILDKITE_PLUGIN_SNYK_ORG"
  export ORG=$BUILDKITE_PLUGIN_SNYK_ORG
fi

# path to dependency file
if [[ -n "$BUILDKITE_PLUGIN_SNYK_PATH" ]]; 
then
  echo "Path: $BUILDKITE_PLUGIN_SNYK_PATH"
  export DEPENDENCY_PATH=$BUILDKITE_PLUGIN_SNYK_PATH
fi

# extract repository name
if [[ -n "$BUILDKITE_REPO" ]]; 
then
  echo "Repository: $BUILDKITE_REPO"
  export REPOSITORY=$(echo $BUILDKITE_REPO | sed 's/.*:// ; s/.git//')
fi

# setting severity
if [[ -n "$BUILDKITE_PLUGIN_SNYK_SEVERITY" ]]; 
then
  echo "Severity: $BUILDKITE_PLUGIN_SNYK_SEVERITY"
  export SEVERITY=$BUILDKITE_PLUGIN_SNYK_SEVERITY
else
  export SEVERITY="low"
fi

# npm token
if [[ -n "$BUILDKITE_PLUGIN_SNYK_TOKEN" ]]; 
then
  export NPM_TOKEN=$(printenv $BUILDKITE_PLUGIN_SNYK_TOKEN)
fi

# artifactory credentials
if [[ -n "$BUILDKITE_PLUGIN_SNYK_ARTIFACTORYUSERNAME" ]]; 
then
  export ARTIFACTORY_USERNAME=$BUILDKITE_PLUGIN_SNYK_ARTIFACTORYUSERNAME
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_ARTIFACTORYPASSWORD" ]]; 
then
  export ARTIFACTORY_PASSWORD=$(printenv $BUILDKITE_PLUGIN_SNYK_ARTIFACTORYPASSWORD)
fi

echo "Running command step!"
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
docker build -q ${DIR}/.. -t docker-snyk:latest
docker run \
  -e SNYK_TOKEN \
  -e REPOSITORY \
  -e ORG \
  -e LANGUAGE \
  -e DEPENDENCY_PATH \
  -e BLOCK \
  -e SEVERITY \
  -e NPM_TOKEN \
  -e ARTIFACTORY_USERNAME \
  -e ARTIFACTORY_PASSWORD \
  -v $DIR/..:/plugin \
  -v `pwd`:/$REPOSITORY docker-snyk:latest