#!/usr/bin/env bash

export VERSION='v1.0.0'
export PLUGIN_NAME='snyk-buildkite-plugin'

echo 'Validating environment variables'

if [[ -n "$EVENTS_TOPIC_ARN" ]];
then
  export METRICS_TOPIC_ARN=$EVENTS_TOPIC_ARN
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_BLOCK" ]];
then
  echo "Block: $BUILDKITE_PLUGIN_SNYK_BLOCK"
  export BLOCK=$BUILDKITE_PLUGIN_SNYK_BLOCK
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_ALLSUBPROJECTS" ]];
then
  echo "All Subprojects: $BUILDKITE_PLUGIN_SNYK_ALLSUBPROJECTS"
  export ALLSUBPROJECTS=$BUILDKITE_PLUGIN_SNYK_ALLSUBPROJECTS
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_LANGUAGE" ]];
then
  echo "Language: $BUILDKITE_PLUGIN_SNYK_LANGUAGE"
  export LANGUAGE=$BUILDKITE_PLUGIN_SNYK_LANGUAGE
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_SCANDEVDEPS" ]];
then
  export SCAN_DEV_DEPS=$BUILDKITE_PLUGIN_SNYK_SCANDEVDEPS
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_ORG" ]];
then
  echo "Org: $BUILDKITE_PLUGIN_SNYK_ORG"
  export ORG=$BUILDKITE_PLUGIN_SNYK_ORG
fi

# path to dependency file
if [[ -n "$BUILDKITE_PLUGIN_SNYK_PATH" ]];
then
  echo "Path: $BUILDKITE_PLUGIN_SNYK_PATH"
  export DEPENDENCY_PATH=$BUILDKITE_PLUGIN_SNYK_PATH
fi

# extract repository name
if [[ -n "$BUILDKITE_REPO" ]];
then
  echo "Repository: $BUILDKITE_REPO"
  export REPOSITORY=$(echo $BUILDKITE_REPO | sed 's/.*:// ; s/.git//')
fi

# extract repository slug
if [[ -n "$BUILDKITE_PIPELINE_SLUG" ]];
then
  echo "Pipeline slug: $BUILDKITE_PIPELINE_SLUG"
  export REPOSITORY_SLUG=$BUILDKITE_PIPELINE_SLUG
fi

# setting severity
if [[ -n "$BUILDKITE_PLUGIN_SNYK_SEVERITY" ]];
then
  echo "Severity: $BUILDKITE_PLUGIN_SNYK_SEVERITY"
  export SEVERITY=$BUILDKITE_PLUGIN_SNYK_SEVERITY
else
  export SEVERITY="low"
fi

# npm token
if [[ -n "$BUILDKITE_PLUGIN_SNYK_NPMTOKEN" ]];
then
  export NPM_TOKEN=$(printenv $BUILDKITE_PLUGIN_SNYK_NPMTOKEN)
fi

if [[ -n "$BUILDKITE_PLUGIN_SNYK_SUBDIRECTORY" ]];
then
  export SUB_DIRECTORY=$BUILDKITE_PLUGIN_SNYK_SUBDIRECTORY
fi

# package manager experimental flag
if [[ -n "$BUILDKITE_PLUGIN_SNYK_PACKAGEMANAGER" ]];
then
  export PACKAGE_MANAGER=$BUILDKITE_PLUGIN_SNYK_PACKAGEMANAGER
fi

# package manager experimental flag
if [[ -n "$BUILDKITE_PLUGIN_SNYK_STRICTOUTOFSYNC" ]];
then
  echo "Strict out of sync: $BUILDKITE_PLUGIN_SNYK_STRICTOUTOFSYNC"
  export STRICT_OUT_OF_SYNC=$BUILDKITE_PLUGIN_SNYK_STRICTOUTOFSYNC
fi

echo "Running command step!"
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
docker build --secret id=npmrc,src="${HOME}/.npmrc" -q ${DIR}/.. -t docker-snyk:latest
docker run \
  -e SUB_DIRECTORY \
  -e PACKAGE_MANAGER \
  -e PLUGIN_NAME \
  -e METRICS_TOPIC_ARN \
  -e VERSION \
  -e SNYK_TOKEN \
  -e REPOSITORY \
  -e REPOSITORY_SLUG \
  -e ORG \
  -e LANGUAGE \
  -e SCAN_DEV_DEPS \
  -e DEPENDENCY_PATH \
  -e BLOCK \
  -e SEVERITY \
  -e NPM_TOKEN \
  -e ARTIFACTORY_URL \
  -e ARTIFACTORY_USERNAME \
  -e ARTIFACTORY_PASSWORD \
  -e ALLSUBPROJECTS \
  -e STRICT_OUT_OF_SYNC \
  -v $DIR/..:/plugin \
  -v `pwd`:/$REPOSITORY docker-snyk:latest
